### ISSUE TITLE
Improvements to be made

### ISSUE THREAD

**Issue by seirdotexe** [LockBlock-dev/earnapp.js#4]
Hi there!

I checked out your repository and it looks great, but I figured there's some improvements to be made. Why not use `node-fetch`? Or the newly available `fetch` feature in Node v18 that doesn't require any extra dependencies? The downside to that would be to force Node v18 in your package.json, but it's great. Also, requiring package.json in every request doesn't seem efficient and there might be a better solution to that. It may as well be nice to look into ES6!

Other than that this repository surely improved my knowledge over creating a Promise based API and I deeply thank you for your work😅

**Comment by LockBlock-dev** [comment]
I'm using `axios` for a long time now and it's working perfectly fine so I'll not switch to `node-fetch`. Also I don't want to limit the lib to Node 18 as it's kinda new.
I made a constant for the package.json since I think it's not efficient to require it at each request too.
Finally I prefer using CommonJS format but the lib can be imported in ES6.

In any case, thanks for this issue I appreciate it.
